name: HTML to APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Compile HTML to APK
        uses: fmaclen/html-to-android@v1.1.0
        with:
          file: "*.html"
          output_dir: "output"

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: my-app-apk
          path: output/*.apk
          
